title: Public Privacy
description: Eine experimentelle Website, die KI nutzt um auf den Datenschutz von Fotos im Internet aufmerksam zu machen. Alle Bilder kommen von Kunden des Modehändlers SHEIN.

about: Über
portfolio: Weitere Projekte
cookie: Diese Website trackt keinerlei Nutzerverhalten. Es wird lediglich ein Cookie für die Spracheinstellung gesetzt.
