title: Public Privacy
description: An experimental project which uses AI to expose privacy in photographs. All images come from customers of  the ultra-fast fashion seller SHEIN.

about: About
portfolio: More Projects
cookie: This website does not track its users. It only sets a cookie to save the language preferences.
